spring:
  #配置启动项目
  config:
    activate:
      on-profile: dev
  #开启支持RFC7807
  mvc:
    problemdetails:
      enabled: true


#配置tomcat
server:
#  port: 80
  tomcat:
    #访问日志
    accesslog:
      #是否开启
      enabled: true
      #日志保存路径
      directory: H:/new project/springBootProject/log
      #日志文件前缀
      prefix: vagmrApi
      #日志文件是否包括时间
      file-date-format: .yyyy-MM-dd-HH
      suffix: .log
    max-connections: 100
#修改日志级别
#logging:
#  level:
#    web: debug




